apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocket
  template:
    metadata:
      labels:
        app: rocket
    spec:
      containers:
      - name: rocket
        image: rocket.chat
        ports:
          - name: http
            containerPort: 31000
            protocol: TCP
        env:
        - name: ROOT_URL
          value: http://localhost:3000/
