apiVersion: v1
kind: PersistentVolume
metadata:
  name: data1-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /tmp/data/handson-pv
